version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "alexa-skill-lambda"
s3_bucket = "aws-sam-cli-managed-default"
s3_prefix = "alexa-skill-lambda"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
