
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  skill-curiosidades

  Sample SAM Template for skill-curiosidades

Parameters:
  AlexaSkillId:
    Type: String
    Description: Alexa Skill Id
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CuriosidadesMonthyPythonLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: skill/
      Handler: Module1.handler
      Runtime: nodejs12.x
      Policies:
        - AWSLambdaBasicExecutionRole      
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: !Ref AlexaSkillId
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LambdaFunctionARN:
    Description: "Function ARN"
    Value: !GetAtt CuriosidadesMonthyPythonLambdaFunction.Arn
